"""baseline_schema_and_api_source_to_text

Revision ID: fa2d1f01156f
Revises: 
Create Date: 2026-04-05 23:36:33.023629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa2d1f01156f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_table('locations')
    op.drop_table('portfolios')
    op.create_index(op.f('ix_data_quality_events_event_type'), 'data_quality_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_data_quality_events_is_resolved'), 'data_quality_events', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_data_quality_events_occurred_at'), 'data_quality_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_data_quality_events_severity'), 'data_quality_events', ['severity'], unique=False)
    op.create_index(op.f('ix_data_quality_events_source_type'), 'data_quality_events', ['source_type'], unique=False)
    op.alter_column('data_source_cache', 'api_source',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_submitted_at'), 'feedback', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_herc_risk_cache_calculated_at'), 'herc_risk_cache', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_herc_risk_cache_is_valid'), 'herc_risk_cache', ['is_valid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_herc_risk_cache_is_valid'), table_name='herc_risk_cache')
    op.drop_index(op.f('ix_herc_risk_cache_calculated_at'), table_name='herc_risk_cache')
    op.drop_index(op.f('ix_feedback_submitted_at'), table_name='feedback')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.alter_column('data_source_cache', 'api_source',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_data_quality_events_source_type'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_severity'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_occurred_at'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_is_resolved'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_event_type'), table_name='data_quality_events')
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('location_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('square_footage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annual_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_assessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('locations_portfolio_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolios_pkey'))
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crime_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('natural_disaster_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('economic_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('competition_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('infrastructure_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('regulatory_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimated_annual_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('risk_assessments_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_assessments_pkey'))
    )
    # ### end Alembic commands ###
